
CREATE TABLE M_CUSTOMER_CLASS
(
	code smallint(4) NOT NULL PRIMARY KEY,
	name varchar(20) NOT NULL,
	kana varchar(20),
	updDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
DEFAULT CHARSET=utf8;
